name: test_journal
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



#  cupertino_icons: ^1.0.6
#  swipe_refresh: ^1.1.2
  mysql_client: ^0.0.27
  http: ^1.2.0
  accordion: ^2.6.0
  date_picker_plus: ^3.0.2
  excel: ^4.0.6
  mailer: ^6.2.0
  flutter_swipe_action_cell: ^3.1.5
  path_provider: ^2.1.5
#  permission_handler: ^11.3.1
  dropdown_button2: ^2.3.9
#  responsive_toolkit: ^0.0.6
  flutter_secure_storage: ^9.2.4
#  crypt: ^4.3.1
  crypto: ^3.0.6
  windows_single_instance: ^1.0.1


dev_dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.0
  filesystem_picker: ^4.0.0


flutter:


  uses-material-design: true

#  assets:
#    - assets/

